# Assignment7

そのまま課題ファイルで編集しないでください。課題ファイルを複製してから課題を回答してください。

## 課題1

pandasでDataフォルダの```example.json```を読み込む。

In [6]:
import pandas as pd

df = pd.read_json("Data/example.json", lines=True)
df

     Name  Price  Model  Power
0   Honda  10000   2005   1300
1  Toyota  12000   2010   1600
2    Audi  25000   2017   1800
3    Ford  28000   2009   1200

## 課題2

pandasでDataフォルダの```state-abbrevs.csv```、```state-areas.csv```、```state-population.csv```を読み込む。

これらのデータを使って、**2010年**アメリカの各州の人口密度を計算しよう。

In [9]:
import pandas as pd

abbrevs = pd.read_csv("Data/state-abbrevs.csv")
areas = pd.read_csv("Data/state-areas.csv")
population = pd.read_csv("Data/state-population.csv")

merged = pd.merge(
    population,
    abbrevs,
    left_on="state/region",
    right_on="abbreviation",
    how="left"
)

merged = pd.merge(
    merged,
    areas,
    on="state",
    how="left"
)

data_2010 = merged[
    (merged["year"] == 2010) &
    (merged["ages"] == "total")
].copy()

data_2010 = data_2010.dropna(
    subset=["state", "area (sq. mi)"]
)

data_2010["population_density"] = (
    data_2010["population"] /
    data_2010["area (sq. mi)"]
)

data_2010[
    ["state", "population", "area (sq. mi)", "population_density"]
].sort_values(
    "population_density",
    ascending=False
)

                     state  population  area (sq. mi)  population_density
389   District of Columbia    605125.0           68.0         8898.897059
1445            New Jersey   8802707.0         8722.0         1009.253268
1914          Rhode Island   1052669.0         1545.0          681.339159
293            Connecticut   3579210.0         5544.0          645.600649
1050         Massachusetts   6563263.0        10555.0          621.815538
965               Maryland   5787193.0        12407.0          466.445797
379               Delaware    899711.0         1954.0          460.445752
1541              New York  19398228.0        54475.0          356.094135
475                Florida  18846054.0        65758.0          286.597129
1829          Pennsylvania  12710472.0        46058.0          275.966651
1722                  Ohio  11545435.0        44828.0          257.549634
197             California  37333601.0       163707.0          228.051342
666               Illinois  12839695.0        57918.0          221.687472
2213              Virginia   8024417.0        42769.0          187.622273
677                Indiana   6489965.0        36420.0          178.197831
1626        North Carolina   9559533.0        53821.0          177.617157
485                Georgia   9713248.0        59441.0          163.409902
2021             Tennessee   6356683.0        42146.0          150.825298
1925        South Carolina   4636361.0        32007.0          144.854594
1434         New Hampshire   1316614.0         9351.0          140.799273
570                 Hawaii   1363731.0        10932.0          124.746707
858               Kentucky   4347698.0        40411.0          107.586994
1061              Michigan   9876149.0        96810.0          102.015794
2298            Washington   6742256.0        71303.0           94.557817
2106                 Texas  25245178.0       268601.0           93.987655
3                  Alabama   4785570.0        52423.0           91.287603
869              Louisiana   4545392.0        51843.0           87.676099
2394             Wisconsin   5689060.0        65503.0           86.851900
1242              Missouri   5996063.0        69709.0           86.015622
2309         West Virginia   1854146.0        24231.0           76.519582
2202               Vermont    625793.0         9615.0           65.085075
1157           Mississippi   2970047.0        48434.0           61.321530
1146             Minnesota   5310337.0        86943.0           61.078373
101                Arizona   6408790.0       114006.0           56.214497
189               Arkansas   2922280.0        53182.0           54.948667
762                   Iowa   3050314.0        56276.0           54.202751
1733              Oklahoma   3759263.0        69903.0           53.778278
283               Colorado   5048196.0       104100.0           48.493718
1818                Oregon   3837208.0        98386.0           39.001565
954                  Maine   1327366.0        35387.0           37.509990
773                 Kansas   2858910.0        82282.0           34.745266
2117                  Utah   2774424.0        84904.0           32.677188
1349                Nevada   2703230.0       110567.0           24.448796
1338              Nebraska   1829838.0        77358.0           23.654153
581                  Idaho   1570718.0        83574.0           18.794338
1530            New Mexico   2064982.0       121593.0           16.982737
2010          South Dakota    816211.0        77121.0           10.583512
1637          North Dakota    674344.0        70704.0            9.537565
1253               Montana    990527.0       147046.0            6.736171
2405               Wyoming    564222.0        97818.0            5.768079
91                  Alaska    713868.0       656425.0            1.087509

## 課題3

```state/region```、```ages```と```years```でデータフレームをグループして、各グループで$\frac{population}{area (sq. mi)}$の形で人口密度を計算してください。

In [8]:
grouped = pd.read_csv("Data/grouped.csv")

def calculate_density(group):
    return (
        group["population"].sum()
        / group["area (sq. mi)"].mean()
    )

population_density = (
    grouped
    .groupby(["state/region", "ages", "year"])
    .apply(calculate_density)
    .reset_index(name="population_density")
)

population_density

     state/region     ages  year  population_density
0              AK    total  1990            0.842884
1              AK    total  1991            0.868634
2              AK    total  1992            0.896882
3              AK    total  1993            0.913180
4              AK    total  1994            0.919081
...           ...      ...   ...                 ...
2443           WY  under18  2009            1.379705
2444           WY  under18  2010            1.383702
2445           WY  under18  2011            1.384275
2446           WY  under18  2012            1.395714
2447           WY  under18  2013            1.407502

[2448 rows x 4 columns]