# Assignment7

そのまま課題ファイルで編集しないでください。課題ファイルを複製してから課題を回答してください。

## 課題1

pandasでDataフォルダの```example.json```を読み込む。

In [15]:
import pandas as pd

df1 = pd.read_json(r"C:\Users\ma_12\Downloads\example.json",
                  lines = True)
df1

     Name  Price  Model  Power
0   Honda  10000   2005   1300
1  Toyota  12000   2010   1600
2    Audi  25000   2017   1800
3    Ford  28000   2009   1200

## 課題2

pandasでDataフォルダの```state-abbrevs.csv```、```state-areas.csv```、```state-population.csv```を読み込む。

これらのデータを使って、**2010年**アメリカの各州の人口密度を計算しよう。

In [68]:
import pandas as pd

df2 = pd.read_csv(r"C:\Users\ma_12\Downloads\state-abbrevs.csv")
df3 = pd.read_csv(r"C:\Users\ma_12\Downloads\state-areas.csv")
df4 =pd.read_csv(r"C:\Users\ma_12\Downloads\state-population.csv")

df4_r = df4[(df4["ages"] == "total") & (df4["year"] == 2010)]
merge1 = pd.merge(df2, df3, how = "left", on="state")
merge2 = pd.merge(merge1, df4_r, how = "right", left_on="abbreviation", right_on="state/region")
merge2
merge2["population_density"] = merge2["population"] / merge2["area (sq. mi)"]
merge2

,state,abbreviation,area (sq. mi),state/region,ages,year,population,population_density
0,Alabama,AL,52423.0,AL,total,2010,4785570.0,91.287603
1,Alaska,AK,656425.0,AK,total,2010,713868.0,1.087509
2,Arizona,AZ,114006.0,AZ,total,2010,6408790.0,56.214497
3,Arkansas,AR,53182.0,AR,total,2010,2922280.0,54.948667
4,California,CA,163707.0,CA,total,2010,37333601.0,228.051342
5,Colorado,CO,104100.0,CO,total,2010,5048196.0,48.493718
6,Connecticut,CT,5544.0,CT,total,2010,3579210.0,645.600649
7,Delaware,DE,1954.0,DE,total,2010,899711.0,460.445752
8,District of Columbia,DC,68.0,DC,total,2010,605125.0,8898.897059
9,Florida,FL,65758.0,FL,total,2010,18846054.0,286.597129
10,Georgia,GA,59441.0,GA,total,2010,9713248.0,163.409902
11,Hawaii,HI,10932.0,HI,total,2010,1363731.0,124.746707
12,Idaho,ID,83574.0,ID,total,2010,1570718.0,18.794338
13,Illinois,IL,57918.0,IL,total,2010,12839695.0,221.687472
14,Indiana,IN,36420.0,IN,total,2010,6489965.0,178.197831
15,Iowa,IA,56276.0,IA,total,2010,3050314.0,54.202751
16,Kansas,KS,82282.0,KS,total,2010,2858910.0,34.745266
17,Kentucky,KY,40411.0,KY,total,2010,4347698.0,107.586994
18,Louisiana,LA,51843.0,LA,total,2010,4545392.0,87.676099
19,Maine,ME,35387.0,ME,total,2010,1327366.0,37.509990
20,Maryland,MD,12407.0,MD,total,2010,5787193.0,466.445797
21,Massachusetts,MA,10555.0,MA,total,2010,6563263.0,621.815538
22,Michigan,MI,96810.0,MI,total,2010,9876149.0,102.015794
23,Minnesota,MN,86943.0,MN,total,2010,5310337.0,61.078373
24,Mississippi,MS,48434.0,MS,total,2010,2970047.0,61.321530
25,Missouri,MO,69709.0,MO,total,2010,5996063.0,86.015622
26,Montana,MT,147046.0,MT,total,2010,990527.0,6.736171
27,Nebraska,NE,77358.0,NE,total,2010,1829838.0,23.654153
28,Nevada,NV,110567.0,NV,total,2010,2703230.0,24.448796
29,New Hampshire,NH,9351.0,NH,total,2010,1316614.0,140.799273
30,New Jersey,NJ,8722.0,NJ,total,2010,8802707.0,1009.253268
31,New Mexico,NM,121593.0,NM,total,2010,2064982.0,16.982737
32,New York,NY,54475.0,NY,total,2010,19398228.0,356.094135
33,North Carolina,NC,53821.0,NC,total,2010,9559533.0,177.617157
34,North Dakota,ND,70704.0,ND,total,2010,674344.0,9.537565
35,Ohio,OH,44828.0,OH,total,2010,11545435.0,257.549634
36,Oklahoma,OK,69903.0,OK,total,2010,3759263.0,53.778278
37,Oregon,OR,98386.0,OR,total,2010,3837208.0,39.001565
38,Pennsylvania,PA,46058.0,PA,total,2010,12710472.0,275.966651
39,Rhode Island,RI,1545.0,RI,total,2010,1052669.0,681.339159
40,South Carolina,SC,32007.0,SC,total,2010,4636361.0,144.854594
41,South Dakota,SD,77121.0,SD,total,2010,816211.0,10.583512
42,Tennessee,TN,42146.0,TN,total,2010,6356683.0,150.825298
43,Texas,TX,268601.0,TX,total,2010,25245178.0,93.987655
44,Utah,UT,84904.0,UT,total,2010,2774424.0,32.677188
45,Vermont,VT,9615.0,VT,total,2010,625793.0,65.085075
46,Virginia,VA,42769.0,VA,total,2010,8024417.0,187.622273
47,Washington,WA,71303.0,WA,total,2010,6742256.0,94.557817
48,West Virginia,WV,24231.0,WV,total,2010,1854146.0,76.519582
49,Wisconsin,WI,65503.0,WI,total,2010,5689060.0,86.851900
50,Wyoming,WY,97818.0,WY,total,2010,564222.0,5.768079
51,NaN,NaN,NaN,PR,total,2010,3721208.0,NaN
52,NaN,NaN,NaN,USA,total,2010,309326295.0,NaN

## 課題3

```state/region```、```ages```と```years```でデータフレームをグループして、各グループで$\frac{population}{area (sq. mi)}$の形で人口密度を計算してください。

In [86]:
merge3 = pd.merge(merge1, df4, how = "right", left_on="abbreviation", right_on="state/region")
merge3["population_density"] = merge3["population"] / merge3["area (sq. mi)"]

merge3.groupby(["state", "ages", "year"])["population_density"].sum()

state    ages     year
Alabama  total    1990    77.257215
                  1991    78.193846
                  1992    79.240295
                  1993    80.388417
                  1994    81.266410
                            ...
Wyoming  under18  2009     1.379705
                  2010     1.383702
                  2011     1.384275
                  2012     1.395714
                  2013     1.407502
Name: population_density, Length: 2448, dtype: float64