# Assignment7

そのまま課題ファイルで編集しないでください。課題ファイルを複製してから課題を回答してください。

## 課題1

pandasでDataフォルダの```example.json```を読み込む。

In [26]:
import pandas as pd

df = pd.read_json("Data/example.json", lines=True)
df

     Name  Price  Model  Power
0   Honda  10000   2005   1300
1  Toyota  12000   2010   1600
2    Audi  25000   2017   1800
3    Ford  28000   2009   1200

## 課題2

pandasでDataフォルダの```state-abbrevs.csv```、```state-areas.csv```、```state-population.csv```を読み込む。

これらのデータを使って、**2010年**アメリカの各州の人口密度を計算しよう。

In [27]:
abbrevs    = pd.read_csv("Data/state-abbrevs.csv")
areas      = pd.read_csv("Data/state-areas.csv")
population = pd.read_csv("Data/state-population.csv")



data_2010 = population[
    (population["year"] == 2010) &
    (population["ages"] == "total")
    ]

data_2010 = data_2010.merge(abbrevs, left_on="state/region", right_on="abbreviation")
data_2010 = data_2010.merge(areas, on="state")

data_2010["density"] = data_2010["population"] / data_2010["area (sq. mi)"]

data_2010[["state", "population", "area (sq. mi)", "density"]]

                   state  population  area (sq. mi)      density
0                Alabama   4785570.0          52423    91.287603
1                 Alaska    713868.0         656425     1.087509
2                Arizona   6408790.0         114006    56.214497
3               Arkansas   2922280.0          53182    54.948667
4             California  37333601.0         163707   228.051342
5               Colorado   5048196.0         104100    48.493718
6            Connecticut   3579210.0           5544   645.600649
7               Delaware    899711.0           1954   460.445752
8   District of Columbia    605125.0             68  8898.897059
9                Florida  18846054.0          65758   286.597129
10               Georgia   9713248.0          59441   163.409902
11                Hawaii   1363731.0          10932   124.746707
12                 Idaho   1570718.0          83574    18.794338
13              Illinois  12839695.0          57918   221.687472
14               Indiana   6489965.0          36420   178.197831
15                  Iowa   3050314.0          56276    54.202751
16                Kansas   2858910.0          82282    34.745266
17              Kentucky   4347698.0          40411   107.586994
18             Louisiana   4545392.0          51843    87.676099
19                 Maine   1327366.0          35387    37.509990
20              Maryland   5787193.0          12407   466.445797
21         Massachusetts   6563263.0          10555   621.815538
22              Michigan   9876149.0          96810   102.015794
23             Minnesota   5310337.0          86943    61.078373
24           Mississippi   2970047.0          48434    61.321530
25              Missouri   5996063.0          69709    86.015622
26               Montana    990527.0         147046     6.736171
27              Nebraska   1829838.0          77358    23.654153
28                Nevada   2703230.0         110567    24.448796
29         New Hampshire   1316614.0           9351   140.799273
30            New Jersey   8802707.0           8722  1009.253268
31            New Mexico   2064982.0         121593    16.982737
32              New York  19398228.0          54475   356.094135
33        North Carolina   9559533.0          53821   177.617157
34          North Dakota    674344.0          70704     9.537565
35                  Ohio  11545435.0          44828   257.549634
36              Oklahoma   3759263.0          69903    53.778278
37                Oregon   3837208.0          98386    39.001565
38          Pennsylvania  12710472.0          46058   275.966651
39          Rhode Island   1052669.0           1545   681.339159
40        South Carolina   4636361.0          32007   144.854594
41          South Dakota    816211.0          77121    10.583512
42             Tennessee   6356683.0          42146   150.825298
43                 Texas  25245178.0         268601    93.987655
44                  Utah   2774424.0          84904    32.677188
45               Vermont    625793.0           9615    65.085075
46              Virginia   8024417.0          42769   187.622273
47            Washington   6742256.0          71303    94.557817
48         West Virginia   1854146.0          24231    76.519582
49             Wisconsin   5689060.0          65503    86.851900
50               Wyoming    564222.0          97818     5.768079

## 課題3

```state/region```、```ages```と```years```でデータフレームをグループして、各グループで$\frac{population}{area (sq. mi)}$の形で人口密度を計算してください。

In [ ]:
merged_data = population.merge(abbrevs, left_on="state/region", right_on="abbreviation")
merged_data = merged_data.merge(areas, on="state")

density_data = (
    merged_data.groupby(["state/region", "ages", "year"])
    .agg({"population": "sum","area (sq. mi)": "first"})
    )

density_data["density"] = (
    density_data["population"]/ density_data["area (sq. mi)"]
)

density_data

                           population  area (sq. mi)   density
state/region ages    year
AK           total   1990    553290.0         656425  0.842884
                     1991    570193.0         656425  0.868634
                     1992    588736.0         656425  0.896882
                     1993    599434.0         656425  0.913180
                     1994    603308.0         656425  0.919081
...                               ...            ...       ...
WY           under18 2009    134960.0          97818  1.379705
                     2010    135351.0          97818  1.383702
                     2011    135407.0          97818  1.384275
                     2012    136526.0          97818  1.395714
                     2013    137679.0          97818  1.407502

[2448 rows x 3 columns]